import Head from "next/head";
import PrimarySearchAppBar from "../components/Header";
import { ProductList } from "../components/ProductList/ProductList";
import { addDataProducts } from "../redux/slices/product-reducer";
import { productApi } from "../api/ProductApi";
import { wrapper } from "../redux/redux-store";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Edelweiss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PrimarySearchAppBar />
        <ProductList />
      </main>
    </div>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (cnx) => {
    const dataProduct = store.getState().product.data;
    console.log(dataProduct);
    if (dataProduct === null) {
      console.log("data null?");
      const data = await productApi.findAll();
      store.dispatch(addDataProducts(data));
      return {
        props: { data },
      };
    }
  }
);
